services:
  tgbot:
    image: $NODE_IMAGE
    container_name: 
      'tgbot'
    working_dir: /usr/src/bot
    volumes:
      - ./bot:/usr/src/bot
    env_file:
        - ./.env
    command: "/bin/sh -c 'yarn start:dev'"
    ports:
        - $APP_PORT:$APP_PORT
        - $DEBUG_PORT:$DEBUG_PORT
